import pytest
import pytest_asyncio
import asyncio
from datetime import datetime, timezone
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.analysis import AnalysisRun
from app.models.metric import MarketMetric
from app.models.insight import Insight
from app.models.company import Company
from app.services.pipeline.orchestrator import run_analysis_pipeline

# We need to mock the extractors and generators so we can test the orchestrator behavior
from unittest.mock import patch, AsyncMock
from app.services.extraction.base import ExtractionResult

@pytest_asyncio.fixture
async def db_session():
    from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker, AsyncSession
    from app.db.base import Base

    engine = create_async_engine("sqlite+aiosqlite:///./test_pipeline.db", echo=False)
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    test_session_factory = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    async with test_session_factory() as session:
        yield session

    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
    await engine.dispose()
    
    import pathlib
    db_file = pathlib.Path("./test_pipeline.db")
    if db_file.exists():
        db_file.unlink()

@pytest_asyncio.fixture
async def sample_company(db_session: AsyncSession):
    c = Company(name="Primary Test", domain="primary.com", is_primary=True)
    db_session.add(c)
    await db_session.flush()
    return c

@pytest_asyncio.fixture
async def sample_analysis(db_session: AsyncSession, sample_company):
    ar = AnalysisRun(company_id=sample_company.id, status="QUEUED")
    db_session.add(ar)
    await db_session.flush()
    return ar

@pytest.mark.asyncio
@patch("app.services.pipeline.orchestrator.WebsiteExtractor.extract")
@patch("app.services.pipeline.orchestrator.GDELTExtractor.extract")
@patch("app.services.pipeline.orchestrator.PageSpeedExtractor.extract")
@patch("app.services.pipeline.orchestrator.InsightGenerator.generate_insight")
@patch("app.services.pipeline.orchestrator.async_session_factory")
@patch("app.services.pipeline.orchestrator.process_unprocessed_documents")
async def test_analysis_id_isolation(
    mock_process, mock_session_factory, mock_insight, mock_pagespeed, mock_gdelt, mock_website, 
    db_session: AsyncSession, sample_analysis, sample_company
):
    """Test that metrics and insights generated by the pipeline have the correct analysis_id."""
    
    # Setup mock session factory to return our test db_session
    from contextlib import asynccontextmanager
    @asynccontextmanager
    async def mock_factory():
        yield db_session
    mock_session_factory.side_effect = mock_factory
    
    mock_website.return_value = [
        ExtractionResult(url="http://primary.com", title="Home", content="Welcome to Primary", source_type="website", metadata={"status_code": 200})
    ]
    mock_gdelt.return_value = []
    mock_pagespeed.return_value = {"performance": 95}
    mock_insight.return_value = {"summary": "AI Summary here", "severity": "info"}
    
    await run_analysis_pipeline(sample_analysis.id)
    
    # Check MarketMetrics
    metrics = (await db_session.execute(
        select(MarketMetric).where(MarketMetric.analysis_id == sample_analysis.id)
    )).scalars().all()
    
    assert len(metrics) > 0
    for m in metrics:
        assert m.analysis_id == sample_analysis.id
        
    # Check Insights
    insights = (await db_session.execute(
        select(Insight).where(Insight.analysis_id == sample_analysis.id)
    )).scalars().all()
    
    assert len(insights) > 0
    for i in insights:
        assert i.analysis_id == sample_analysis.id

@pytest.mark.asyncio
@patch("app.services.pipeline.orchestrator.WebsiteExtractor.extract")
@patch("app.services.pipeline.orchestrator.GDELTExtractor.extract")
@patch("app.services.pipeline.orchestrator.PageSpeedExtractor.extract")
@patch("app.services.pipeline.orchestrator.InsightGenerator.generate_insight")
@patch("app.services.pipeline.orchestrator.async_session_factory")
@patch("app.services.pipeline.orchestrator.process_unprocessed_documents")
async def test_source_extraction_failure(
    mock_process, mock_session_factory, mock_insight, mock_pagespeed, mock_gdelt, mock_website, 
    db_session: AsyncSession, sample_analysis, sample_company
):
    """Test that the pipeline handles source extraction failures gracefully."""
    
    # Setup mock session factory to return our test db_session
    from contextlib import asynccontextmanager
    @asynccontextmanager
    async def mock_factory():
        yield db_session
    mock_session_factory.side_effect = mock_factory
    
    # Simulate website extractor failure
    mock_website.side_effect = Exception("Website crawl failed")
    mock_gdelt.return_value = []
    mock_pagespeed.return_value = {"performance": 95}
    mock_insight.return_value = {"summary": "AI Summary here", "severity": "info"}
    
    await run_analysis_pipeline(sample_analysis.id)
    
    # Check if analysis run status is PARTIAL
    await db_session.refresh(sample_analysis)
    assert sample_analysis.status == "PARTIAL"
    
    # The SEO metric should still exist but be 0.0 with unavailable status
    metrics = (await db_session.execute(
        select(MarketMetric).where(MarketMetric.analysis_id == sample_analysis.id, MarketMetric.metric_name == "Technical SEO Score")
    )).scalars().all()
    
    assert len(metrics) == 1
    assert metrics[0].metric_value == 0.0
    assert metrics[0].components["status"] == "unavailable"

@pytest.mark.asyncio
async def test_topics_isolation(db_session: AsyncSession):
    from app.models.topic import Topic, DocumentTopic
    from app.models.document import Document
    
    # Create test docs
    d1 = Document(company_id=1, source_id=1, url="http://1", content="Cloud computing AI")
    d2 = Document(company_id=1, source_id=1, url="http://2", content="Machine learning AI")
    db_session.add_all([d1, d2])
    await db_session.flush()
    
    from app.services.nlp.topics import extract_deterministic_topics
    res = extract_deterministic_topics([d1.content, d2.content])
    
    assert res["status"] == "AVAILABLE"
    assert len(res["topics"]) > 0
