"""add analysis runs

Revision ID: 0b45cf0a5571
Revises: 29ba8b50f1ba
Create Date: 2026-09-15 19:11:06.741491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b45cf0a5571'
down_revision: Union[str, None] = '29ba8b50f1ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_runs_company', 'analysis_runs', ['company_id'], unique=False)
    op.create_index('ix_analysis_runs_status', 'analysis_runs', ['status'], unique=False)
    op.create_table('analysis_competitors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competitor_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_competitors_company', 'analysis_competitors', ['competitor_id'], unique=False)
    op.create_index('ix_analysis_competitors_run', 'analysis_competitors', ['analysis_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analysis_competitors_run', table_name='analysis_competitors')
    op.drop_index('ix_analysis_competitors_company', table_name='analysis_competitors')
    op.drop_table('analysis_competitors')
    op.drop_index('ix_analysis_runs_status', table_name='analysis_runs')
    op.drop_index('ix_analysis_runs_company', table_name='analysis_runs')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
