import { useState, useEffect } from 'react'
import { useQuery } from '@tanstack/react-query'
import { insightsApi } from '@/api/insights'
import { useWorkspaceEntities } from '@/hooks/useWorkspaceEntities'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Skeleton } from '@/components/ui/skeleton'
import { Badge } from '@/components/ui/badge'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { BrainCircuit } from 'lucide-react'

export default function Intelligence() {
  const { allEntities, selectedCompanyId: workspaceCompanyId } = useWorkspaceEntities()
  const [localCompanyId, setLocalCompanyId] = useState<number | undefined>(workspaceCompanyId || undefined)

  useEffect(() => {
    if (workspaceCompanyId && !localCompanyId) {
      setLocalCompanyId(workspaceCompanyId)
    }
  }, [workspaceCompanyId, localCompanyId])

  const { data: insightsPage, isLoading: isInsightsLoading } = useQuery({
    queryKey: ['insights', localCompanyId],
    queryFn: () => insightsApi.getInsights({ company_id: localCompanyId, page_size: 20 })
  })

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-3xl font-serif tracking-tight">AI Intelligence</h2>
          <p className="text-muted-foreground mt-1">
            Synthesized strategic intelligence from unstructured market data.
          </p>
        </div>
        
        <div className="w-full sm:w-[250px]">
          <Select 
            value={localCompanyId ? localCompanyId.toString() : "all"} 
            onValueChange={(val) => setLocalCompanyId(val === "all" ? undefined : Number(val))}
          >
            <SelectTrigger>
              <SelectValue placeholder="All Workspace Entities" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Workspace Entities</SelectItem>
              {allEntities.map(c => (
                <SelectItem key={c.id} value={c.id.toString()}>{c.name}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>

      <Card className="shadow-sm">
        <CardHeader>
          <CardTitle className="font-serif text-xl flex items-center gap-2">
            <BrainCircuit className="h-5 w-5" />
            Strategic Syntheses
          </CardTitle>
          <CardDescription>
            Automated intelligence reports generated by the LLM pipeline.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {isInsightsLoading ? (
            <div className="space-y-4">
              <Skeleton className="h-32 w-full rounded-md" />
              <Skeleton className="h-32 w-full rounded-md" />
            </div>
          ) : insightsPage && insightsPage.items.length > 0 ? (
            <div className="grid gap-6">
              {insightsPage.items.map(insight => (
                <div key={insight.id} className="rounded-xl border bg-card p-6 shadow-sm">
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-4">
                    <div className="flex items-center gap-2">
                      <Badge variant="outline" className="font-mono bg-secondary">
                        {allEntities.find(c => c.id === insight.company_id)?.ticker || 
                         allEntities.find(c => c.id === insight.company_id)?.name || "Unknown"}
                      </Badge>
                      <Badge>{insight.insight_type.replace(/_/g, ' ')}</Badge>
                    </div>
                    <div className="text-xs text-muted-foreground font-medium">
                      Generated: {new Date(insight.generated_at).toLocaleString()}
                    </div>
                  </div>
                  
                  <div className="prose prose-sm dark:prose-invert max-w-none">
                    {typeof insight.content === 'string' ? (
                      <p className="whitespace-pre-wrap leading-relaxed">{insight.content}</p>
                    ) : insight.content?.summary ? (
                      <div>
                        <p className="font-medium text-primary mb-2">Executive Summary</p>
                        <p className="leading-relaxed mb-4">{insight.content.summary}</p>
                        
                        {insight.content.key_points && (
                          <>
                            <p className="font-medium text-primary mb-2">Key Findings</p>
                            <ul className="list-disc pl-5 space-y-1">
                              {insight.content.key_points.map((point: string, i: number) => (
                                <li key={i}>{point}</li>
                              ))}
                            </ul>
                          </>
                        )}
                      </div>
                    ) : (
                      <pre className="bg-secondary p-4 rounded-md overflow-x-auto text-xs">
                        {JSON.stringify(insight.content, null, 2)}
                      </pre>
                    )}
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="flex h-[300px] items-center justify-center rounded-lg border border-dashed">
              <p className="text-sm text-muted-foreground">No insights found for the selected criteria.</p>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
